# Generated by Django 4.1.7 on 2023-03-10 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=40)),
                ('img', models.ImageField(default='images/img-error.png', upload_to='')),
                ('style', models.CharField(default='not specified', max_length=70)),
                ('type', models.CharField(choices=[('T', 'Top'), ('B', 'Bottom'), ('S', 'Shoe')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=50)),
                ('color_palette', models.CharField(max_length=50)),
                ('top_styles', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField(verbose_name='Date Made')),
                ('event', models.CharField(max_length=40)),
                ('caption', models.CharField(max_length=50)),
                ('apparels', models.ManyToManyField(to='main_app.apparel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
